spring:
  application:
    name: aidemo

  ai:
    ollama:
      init:
        pull-model-strategy: when_missing
        chat:
          additional-models:
            - gemma2
      chat:
        options:
          temperature: 0.7
          stream: true
          model: gemma2

logging:
  level:
    org.zalando.logbook: TRACE

logbook:
  format:
    style: http