spring:
  application:
    name: aidemo

  ai:
    ollama:
      init:
        pull-model-strategy: when_missing
        chat:
          additional-models:
            - gemma2
      chat:
        options:
          temperature: 0.7
          stream: true
          model: gemma2
    vectorstore:
      mongodb:
        initialize-schema: true
        uri: mongodb://localhost:27017/aidemo
        database: aidemo
        collection: vectorstore
  cloud:
    function:
      definition: fileSupplier|documentReader|splitter|titleDeterminer|vectorStoreConsumer


logging:
  level:
    org.zalando.logbook: TRACE

logbook:
  format:
    style: http
file:
  supplier:
    directory: /path/to/files
    filename-regex: .*\.txt